### ISSUE TITLE
npm run build-linux fails

### ISSUE THREAD

**Issue by s-a** [sulu-one/sulu#35]
```bash

npm run build-linux

Packaging for linux ia32 using electron 1.4.12 to dist\linux-ia32-unpacked
⚠️  Application icon is not set, default Electron icon will be used
Building AppImage for arch ia32
Error: Exit code: ENOENT. spawn C:\Users\User\AppData\Local\electron-builder\cache\AppImage\AppImage-09-07-16-linux\xorriso ENOENT
    at C:\git\sulu\node_modules\electron-builder\src\util\util.ts:77:16
    at exithandler (child_process.js:218:5)
    at ChildProcess.errorhandler (child_process.js:230:5)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:188:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:213:12)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
From previous event:
    at exec (C:\git\sulu\node_modules\electron-builder\src\util\util.ts:55:3)
    at C:\git\sulu\node_modules\electron-builder\src\targets\appImage.ts:74:11
    at Generator.next (<anonymous>)
From previous event:
    at AppImageTarget.build (C:\git\sulu\node_modules\electron-builder\out\targets\appImage.js:144:11)
    at postAsyncTasks.push.default.map.it (C:\git\sulu\node_modules\electron-builder\src\platformPackager.ts:170:85)
From previous event:
    at LinuxPackager.packageInDistributableFormat (C:\git\sulu\node_modules\electron-builder\src\platformPackager.ts:170:41)
    at C:\git\sulu\node_modules\electron-builder\src\platformPackager.ts:166:10
From previous event:
    at LinuxPackager.pack (C:\git\sulu\node_modules\electron-builder\out\platformPackager.js:219:11)
    at C:\git\sulu\node_modules\electron-builder\src\packager.ts:146:22
From previous event:
    at Packager.doBuild (C:\git\sulu\node_modules\electron-builder\out\packager.js:275:11)
    at C:\git\sulu\node_modules\electron-builder\src\packager.ts:114:38
    at Generator.next (<anonymous>)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
From previous event:
    at Packager.build (C:\git\sulu\node_modules\electron-builder\out\packager.js:227:11)
    at Object.<anonymous> (C:\git\sulu\node_modules\electron-builder\src\builder.ts:241:40)
    at Generator.next (<anonymous>)
From previous event:
    at Object.build (C:\git\sulu\node_modules\electron-builder\out\builder.js:89:21)
    at Object.<anonymous> (C:\git\sulu\lib\build.js:28:9)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```
@pmros are you able to fix this issue?

**Comment by s-a** [comment]
I prepared the linux build at https://github.com/sulu-one/sulu/commit/d5f306ae9c2eeb5d7e2556777851c32097df3996
